apiVersion: v1
kind: Service
metadata:
  name: {{ include "study-planner-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "study-planner-chart.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}